# -  /DARK YASIYA/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/CyberWarriorsX/DARK-YASIYA-MD /root/CyberWarriorsX
WORKDIR /root/CyberWarriorsX/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /DARK YASIYA X TEAM/
